### ISSUE TITLE
--type cleanSVs

### ISSUE THREAD

**Issue by zhoudreames** [YaoZhou89/WGSc#1]
您好，在您的泛基因文章中，SV需要经过cleanSVs处理，这一步具体是做什么呢？

**Comment by zhoudreames** [comment]
另外，下面这一步重新mapping 20个个体的步骤不是很理解，并且一共有31个个体，为什么只选择了20个个体重新mapping？
![image](https://user-images.githubusercontent.com/54714639/174430737-f8036641-2aa3-4c39-ad66-2a0b4c820fa5.png)

**Comment by YaoZhou89** [comment]
> 

之前caller里对SVs的定义不一样，有些是把长度大于30bp的也当做SV了，但是我们的定义是50bp。所以clean SVs这步是把长度低于50bp的变异去掉。

**Comment by YaoZhou89** [comment]
> 另外，下面这一步重新mapping 20个个体的步骤不是很理解，并且一共有31个个体，为什么只选择了20个个体重新mapping？ ![image](https://user-images.githubusercontent.com/54714639/174430737-f8036641-2aa3-4c39-ad66-2a0b4c820fa5.png)

这步vg流程使用的用来去除重复SVs的。相同的SV不同的软件去做，检测的不完全一致。这里的20个样本，不是三代，是20个多样性丰富的高深度的二代个体。需要注意的是，这步有可能去除多等位的SVs。

**Comment by zhoudreames** [comment]
谢谢您的回复，明白了

**Comment by zhoudreames** [comment]
另外,WGS --model vcf --type mergeSVs 这个mergeSV的操作的具体功能是什么呢？ 我使用这个命令原本有8W个SV 后面merge一下变成了7W，不知道这一步为什么会减少SV的数量。

**Comment by YaoZhou89** [comment]
这步是根据vg软件要求准备的输入，是否需要merge看你们的实际情况。merge的时候，若ref或者alt的碱基中有N，则会被过滤掉。因为这些都个性化处理，所以我们没有对每个参数进行详细说明，每个参数的功能，可参考WGS源码。

**Comment by zhoudreames** [comment]
好的 谢谢您
